<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_next_receipe_photo</name>
   <tag></tag>
   <elementGuidId>873d8b68-4079-452d-8a7b-451a5d4e481f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ugc-recipe-reviews']/div[@class='ugc-review-nav']/span[@class='ugc-review-next']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
